#All ${..} are coming from .env file, this should only exist in production ready containers
version: '3.9'

services:
  web-dev:
    container_name: web-dev
    image: web-dev:1.0.0
    build:
      context: ./web
      target: development
      dockerfile: ./Dockerfile
    command: npm start
    depends_on:
      - api-dev
    environment:
      API_HOST: api-dev
    ports:
      - ${WEB_PORT}:${WEB_CONTAINER_PORT}
    volumes:
      - ./web:/usr/src/app
    restart: unless-stopped

  api-dev:
    container_name: api-dev
    image: api-dev:1.0.0
    build:
      context: ./api
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    depends_on:
      - mariadb
    environment:
      API_PORT: ${API_CONTAINER_PORT}
      API_PREFIX: '/api'
      DB_HOST: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
    ports:
      - ${API_PORT}:${API_CONTAINER_PORT}
      - 9229:9229
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mariadb:
    container_name: ${DB_HOSTNAME}
    image: mariadb
    command: --init-file /data/application/init.sql
    ports:
      - 3309:3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'invo_passenger'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - ./tools/mariadb/init.sql:/data/application/init.sql
      - ./tools/mariadb/conf.d:/etc/mysql/conf.d
