#All ${..} are coming from .env file, this should only exist in production ready containers
version: '3.9'

services:
  # web:
  #   build: ./web
  #   container_name: web
  #   command: ['npm', 'start']
  #   depends_on:
  #     - api
  #   environment:
  #     PORT: ${WEB_CONTAINER_PORT}
  #   ports:
  #     - ${WEB_PORT}:${WEB_CONTAINER_PORT}
  #   restart: always
  #   volumes:
  #     - ./web:/usr/src/app

  api-dev:
    container_name: api-dev
    image: api-dev:1.0.0
    build:
      context: ./api
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    depends_on:
      - db
    environment:
      API_PREFIX: '/api'
      PORT: ${API_CONTAINER_PORT}
    ports:
      - ${API_PORT}:${API_CONTAINER_PORT}
      - 9229:9229
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  api-prod:
    container_name: api-prod
    image: api-prod:1.0.0
    build:
      context: ./api
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    depends_on:
      - db
    environment:
      API_PREFIX: '/api'
      PORT: ${API_CONTAINER_PORT}
    ports:
      - ${API_PROD_PORT}:${API_CONTAINER_PORT}
      - 9230:9230
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  db:
    container_name: api-db
    image: mariadb
    command: --init-file /data/application/init.sql
    ports:
      - 3309:3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'invo_passenger'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - ./tools/mariadb/init.sql:/data/application/init.sql
      - ./tools/mariadb/conf.d:/etc/mysql/conf.d
